import type { Allergen, MenuItem } from "@palate/core";

const ALL: MealPeriod[] = ["Breakfast", "Lunch", "Dinner"];
type MealPeriod = "Breakfast" | "Lunch" | "Dinner";
const LD: MealPeriod[] = ["Lunch", "Dinner"];
const B: MealPeriod[] = ["Breakfast"];

const ITEMS: MenuItem[] = [
  // ---------------- VILLAGE ----------------
  {
    id: "v-grilled-chicken",
    name: "Grilled Chicken Breast",
    hall: "village",
    station: "Grill",
    role: "protein",
    meals: LD,
    unit: "tong",
    unitPlural: "tongs",
    kcal: 120,
    protein: 24,
    carbs: 0,
    fat: 3,
    tags: ["halal", "gluten-free", "dairy-free"],
  },
  {
    id: "v-carne-asada",
    name: "Carne Asada",
    hall: "village",
    station: "Grill",
    role: "protein",
    meals: LD,
    unit: "tong",
    unitPlural: "tongs",
    kcal: 165,
    protein: 20,
    carbs: 1,
    fat: 9,
    tags: ["gluten-free", "dairy-free"],
  },
  {
    id: "v-salmon",
    name: "Roasted Salmon Fillet",
    hall: "village",
    station: "Hot Line",
    role: "protein",
    meals: ["Dinner"],
    unit: "fillet",
    unitPlural: "fillets",
    kcal: 230,
    protein: 26,
    carbs: 0,
    fat: 14,
    tags: ["gluten-free", "dairy-free"],
  },
  {
    id: "v-tofu",
    name: "Sesame Baked Tofu",
    hall: "village",
    station: "Hot Line",
    role: "protein",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 95,
    protein: 11,
    carbs: 4,
    fat: 5,
    tags: ["vegetarian", "vegan", "halal", "dairy-free"],
  },
  {
    id: "v-cilantro-rice",
    name: "Cilantro Lime Rice",
    hall: "village",
    station: "Hot Line",
    role: "carb",
    meals: LD,
    unit: "rounded ladle",
    unitPlural: "rounded ladles",
    kcal: 180,
    protein: 4,
    carbs: 38,
    fat: 2,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "v-sweet-potato",
    name: "Roasted Sweet Potato",
    hall: "village",
    station: "Hot Line",
    role: "carb",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 110,
    protein: 2,
    carbs: 24,
    fat: 2,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "v-whole-wheat-pasta",
    name: "Whole Wheat Penne",
    hall: "village",
    station: "Pasta Bar",
    role: "carb",
    meals: LD,
    unit: "ladle",
    unitPlural: "ladles",
    kcal: 200,
    protein: 8,
    carbs: 41,
    fat: 2,
    tags: ["vegetarian", "vegan", "halal", "dairy-free"],
  },
  {
    id: "v-broccoli",
    name: "Roasted Broccoli",
    hall: "village",
    station: "Hot Line",
    role: "veg",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 45,
    protein: 3,
    carbs: 6,
    fat: 2,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "v-green-salad",
    name: "Spring Mix Salad",
    hall: "village",
    station: "Salad Bar",
    role: "veg",
    meals: LD,
    unit: "handful",
    unitPlural: "handfuls",
    kcal: 25,
    protein: 2,
    carbs: 4,
    fat: 0,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "v-chickpeas",
    name: "Marinated Chickpeas",
    hall: "village",
    station: "Salad Bar",
    role: "protein",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 105,
    protein: 6,
    carbs: 16,
    fat: 3,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "v-eggs",
    name: "Scrambled Eggs",
    hall: "village",
    station: "Breakfast Line",
    role: "protein",
    meals: B,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 90,
    protein: 8,
    carbs: 1,
    fat: 6,
    tags: ["vegetarian", "halal", "gluten-free"],
  },
  {
    id: "v-oatmeal",
    name: "Steel Cut Oatmeal",
    hall: "village",
    station: "Breakfast Line",
    role: "carb",
    meals: B,
    unit: "ladle",
    unitPlural: "ladles",
    kcal: 150,
    protein: 5,
    carbs: 27,
    fat: 3,
    tags: ["vegetarian", "vegan", "halal", "dairy-free"],
  },
  {
    id: "v-turkey-sausage",
    name: "Turkey Sausage Links",
    hall: "village",
    station: "Breakfast Line",
    role: "protein",
    meals: B,
    unit: "link",
    unitPlural: "links",
    kcal: 70,
    protein: 7,
    carbs: 1,
    fat: 4,
    tags: ["gluten-free", "dairy-free"],
  },
  {
    id: "v-berries",
    name: "Mixed Berries",
    hall: "village",
    station: "Fruit Bar",
    role: "extra",
    meals: ALL,
    unit: "scoop",
    unitPlural: "scoops",
    kcal: 40,
    protein: 1,
    carbs: 9,
    fat: 0,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "v-greek-yogurt",
    name: "Nonfat Greek Yogurt",
    hall: "village",
    station: "Breakfast Line",
    role: "protein",
    meals: ["Breakfast", "Lunch"],
    unit: "scoop",
    unitPlural: "scoops",
    kcal: 80,
    protein: 14,
    carbs: 6,
    fat: 0,
    tags: ["vegetarian", "halal", "gluten-free"],
  },

  // ---------------- EVK ----------------
  {
    id: "e-mongolian-chicken",
    name: "Mongolian Wok Chicken",
    hall: "evk",
    station: "Mongolian",
    role: "protein",
    meals: LD,
    unit: "tong",
    unitPlural: "tongs",
    kcal: 135,
    protein: 22,
    carbs: 4,
    fat: 4,
    tags: ["halal", "dairy-free"],
  },
  {
    id: "e-wok-tofu",
    name: "Wok Tofu & Peppers",
    hall: "evk",
    station: "Mongolian",
    role: "protein",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 100,
    protein: 10,
    carbs: 6,
    fat: 5,
    tags: ["vegetarian", "vegan", "halal", "dairy-free"],
  },
  {
    id: "e-brown-rice",
    name: "Steamed Brown Rice",
    hall: "evk",
    station: "Mongolian",
    role: "carb",
    meals: LD,
    unit: "rounded ladle",
    unitPlural: "rounded ladles",
    kcal: 170,
    protein: 4,
    carbs: 36,
    fat: 1,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "e-lo-mein",
    name: "Veggie Lo Mein",
    hall: "evk",
    station: "Mongolian",
    role: "carb",
    meals: LD,
    unit: "tong",
    unitPlural: "tongs",
    kcal: 190,
    protein: 6,
    carbs: 33,
    fat: 4,
    tags: ["vegetarian", "vegan", "halal", "dairy-free"],
  },
  {
    id: "e-rotisserie",
    name: "Rotisserie Turkey",
    hall: "evk",
    station: "Carving",
    role: "protein",
    meals: ["Dinner"],
    unit: "slice",
    unitPlural: "slices",
    kcal: 85,
    protein: 17,
    carbs: 0,
    fat: 2,
    tags: ["halal", "gluten-free", "dairy-free"],
  },
  {
    id: "e-meatballs",
    name: "Beef Meatballs",
    hall: "evk",
    station: "Hot Line",
    role: "protein",
    meals: LD,
    unit: "meatball",
    unitPlural: "meatballs",
    kcal: 75,
    protein: 6,
    carbs: 2,
    fat: 5,
    tags: ["dairy-free"],
  },
  {
    id: "e-mashed",
    name: "Garlic Mashed Potatoes",
    hall: "evk",
    station: "Hot Line",
    role: "carb",
    meals: ["Dinner"],
    unit: "scoop",
    unitPlural: "scoops",
    kcal: 160,
    protein: 3,
    carbs: 26,
    fat: 5,
    tags: ["vegetarian", "gluten-free"],
  },
  {
    id: "e-green-beans",
    name: "Garlic Green Beans",
    hall: "evk",
    station: "Hot Line",
    role: "veg",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 35,
    protein: 2,
    carbs: 6,
    fat: 1,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "e-kale-salad",
    name: "Lemon Kale Salad",
    hall: "evk",
    station: "Salad Bar",
    role: "veg",
    meals: LD,
    unit: "handful",
    unitPlural: "handfuls",
    kcal: 40,
    protein: 2,
    carbs: 5,
    fat: 2,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "e-edamame",
    name: "Shelled Edamame",
    hall: "evk",
    station: "Salad Bar",
    role: "protein",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 60,
    protein: 6,
    carbs: 5,
    fat: 2,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "e-egg-whites",
    name: "Egg White Scramble",
    hall: "evk",
    station: "Breakfast Line",
    role: "protein",
    meals: B,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 45,
    protein: 9,
    carbs: 1,
    fat: 0,
    tags: ["vegetarian", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "e-potatoes",
    name: "Breakfast Potatoes",
    hall: "evk",
    station: "Breakfast Line",
    role: "carb",
    meals: B,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 120,
    protein: 2,
    carbs: 20,
    fat: 4,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "e-pancake",
    name: "Buttermilk Pancake",
    hall: "evk",
    station: "Breakfast Line",
    role: "carb",
    meals: B,
    unit: "pancake",
    unitPlural: "pancakes",
    kcal: 145,
    protein: 4,
    carbs: 26,
    fat: 3,
    tags: ["vegetarian"],
  },
  {
    id: "e-banana",
    name: "Whole Banana",
    hall: "evk",
    station: "Fruit Bar",
    role: "extra",
    meals: ALL,
    unit: "banana",
    unitPlural: "bananas",
    kcal: 105,
    protein: 1,
    carbs: 27,
    fat: 0,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },

  // ---------------- PARKSIDE ----------------
  {
    id: "p-lemon-chicken",
    name: "Lemon Herb Chicken",
    hall: "parkside",
    station: "Hot Line",
    role: "protein",
    meals: LD,
    unit: "tong",
    unitPlural: "tongs",
    kcal: 130,
    protein: 23,
    carbs: 1,
    fat: 4,
    tags: ["halal", "gluten-free", "dairy-free"],
  },
  {
    id: "p-shrimp",
    name: "Garlic Shrimp",
    hall: "parkside",
    station: "Hot Line",
    role: "protein",
    meals: ["Dinner"],
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 90,
    protein: 16,
    carbs: 1,
    fat: 3,
    tags: ["gluten-free", "dairy-free"],
  },
  {
    id: "p-falafel",
    name: "Baked Falafel",
    hall: "parkside",
    station: "Mezze",
    role: "protein",
    meals: LD,
    unit: "falafel",
    unitPlural: "falafels",
    kcal: 60,
    protein: 3,
    carbs: 7,
    fat: 3,
    tags: ["vegetarian", "vegan", "halal", "dairy-free"],
  },
  {
    id: "p-quinoa",
    name: "Herbed Quinoa",
    hall: "parkside",
    station: "Mezze",
    role: "carb",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 120,
    protein: 5,
    carbs: 21,
    fat: 2,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "p-jasmine-rice",
    name: "Jasmine Rice",
    hall: "parkside",
    station: "Hot Line",
    role: "carb",
    meals: LD,
    unit: "rounded ladle",
    unitPlural: "rounded ladles",
    kcal: 175,
    protein: 4,
    carbs: 39,
    fat: 0,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "p-pizza",
    name: "Margherita Pizza Slice",
    hall: "parkside",
    station: "Pizza Oven",
    role: "carb",
    meals: LD,
    unit: "slice",
    unitPlural: "slices",
    kcal: 245,
    protein: 11,
    carbs: 30,
    fat: 9,
    tags: ["vegetarian"],
  },
  {
    id: "p-zucchini",
    name: "Grilled Zucchini",
    hall: "parkside",
    station: "Hot Line",
    role: "veg",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 30,
    protein: 1,
    carbs: 4,
    fat: 1,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "p-roasted-carrots",
    name: "Honey Roasted Carrots",
    hall: "parkside",
    station: "Hot Line",
    role: "veg",
    meals: LD,
    unit: "spoonful",
    unitPlural: "spoonfuls",
    kcal: 55,
    protein: 1,
    carbs: 11,
    fat: 1,
    tags: ["vegetarian", "gluten-free", "dairy-free"],
  },
  {
    id: "p-caesar",
    name: "Romaine Caesar Base",
    hall: "parkside",
    station: "Salad Bar",
    role: "veg",
    meals: LD,
    unit: "handful",
    unitPlural: "handfuls",
    kcal: 35,
    protein: 2,
    carbs: 4,
    fat: 1,
    tags: ["vegetarian", "halal", "gluten-free"],
  },
  {
    id: "p-black-beans",
    name: "Cumin Black Beans",
    hall: "parkside",
    station: "Mezze",
    role: "protein",
    meals: LD,
    unit: "ladle",
    unitPlural: "ladles",
    kcal: 115,
    protein: 7,
    carbs: 20,
    fat: 1,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "p-cottage",
    name: "Cottage Cheese",
    hall: "parkside",
    station: "Breakfast Line",
    role: "protein",
    meals: B,
    unit: "scoop",
    unitPlural: "scoops",
    kcal: 90,
    protein: 12,
    carbs: 4,
    fat: 3,
    tags: ["vegetarian", "halal", "gluten-free"],
  },
  {
    id: "p-avocado-toast",
    name: "Avocado Toast",
    hall: "parkside",
    station: "Breakfast Line",
    role: "carb",
    meals: B,
    unit: "slice",
    unitPlural: "slices",
    kcal: 190,
    protein: 6,
    carbs: 22,
    fat: 9,
    tags: ["vegetarian", "vegan", "halal", "dairy-free"],
  },
  {
    id: "p-hard-egg",
    name: "Hard Boiled Egg",
    hall: "parkside",
    station: "Breakfast Line",
    role: "protein",
    meals: ALL,
    unit: "egg",
    unitPlural: "eggs",
    kcal: 72,
    protein: 6,
    carbs: 1,
    fat: 5,
    tags: ["vegetarian", "halal", "gluten-free", "dairy-free"],
  },
  {
    id: "p-melon",
    name: "Cut Honeydew",
    hall: "parkside",
    station: "Fruit Bar",
    role: "extra",
    meals: ALL,
    unit: "scoop",
    unitPlural: "scoops",
    kcal: 35,
    protein: 1,
    carbs: 9,
    fat: 0,
    tags: ["vegetarian", "vegan", "halal", "gluten-free", "dairy-free"],
  },
];

/** Known allergens per menu item id. Unlisted means none listed, not allergen-free. */
const ITEM_ALLERGENS: Record<string, Allergen[]> = {
  // Village
  "v-salmon": ["fish"],
  "v-tofu": ["soy", "sesame"],
  "v-whole-wheat-pasta": ["wheat"],
  "v-eggs": ["egg"],
  "v-greek-yogurt": ["milk"],
  // EVK
  "e-mongolian-chicken": ["soy", "wheat", "sesame"],
  "e-wok-tofu": ["soy", "sesame"],
  "e-lo-mein": ["wheat", "soy"],
  "e-meatballs": ["wheat", "egg"],
  "e-mashed": ["milk"],
  "e-edamame": ["soy"],
  "e-egg-whites": ["egg"],
  "e-pancake": ["wheat", "egg", "milk"],
  // Parkside
  "p-shrimp": ["shellfish"],
  "p-falafel": ["sesame"],
  "p-pizza": ["wheat", "milk"],
  "p-caesar": ["egg", "fish"],
  "p-cottage": ["milk"],
  "p-avocado-toast": ["wheat"],
  "p-hard-egg": ["egg"],
};

export const MENU: MenuItem[] = ITEMS.map((item) => ({
  ...item,
  allergens: ITEM_ALLERGENS[item.id] ?? [],
}));

export function portionLabel(item: MenuItem, qty: number) {
  return `${qty} ${qty === 1 ? item.unit : item.unitPlural}`;
}
