import type { MenuItem, Profile } from "./types";

export const profile = (overrides: Partial<Profile> = {}): Profile => ({
  name: "Tommy",
  age: 19,
  gender: "female",
  heightIn: 65,
  weightLb: 130,
  goal: "maintain",
  diets: [],
  allergies: [],
  dislikes: [],
  hall: "village",
  ...overrides,
});

export const item = (overrides: Partial<MenuItem> & Pick<MenuItem, "id">): MenuItem => ({
  name: overrides.id,
  hall: "village",
  station: "Grill",
  role: "protein",
  meals: ["Lunch", "Dinner"],
  unit: "tong",
  unitPlural: "tongs",
  kcal: 100,
  protein: 10,
  carbs: 10,
  fat: 3,
  tags: [],
  ...overrides,
});

export const menu: MenuItem[] = [
  item({
    id: "chicken",
    name: "Grilled Chicken",
    role: "protein",
    kcal: 140,
    protein: 26,
    carbs: 0,
    fat: 3,
  }),
  item({
    id: "tofu",
    name: "Baked Tofu",
    role: "protein",
    kcal: 90,
    protein: 10,
    carbs: 2,
    fat: 5,
    tags: ["vegetarian", "vegan"],
    allergens: ["soy"],
  }),
  item({
    id: "rice",
    name: "Brown Rice",
    role: "carb",
    kcal: 110,
    protein: 2,
    carbs: 23,
    fat: 1,
    tags: ["vegetarian", "vegan"],
  }),
  item({
    id: "broccoli",
    name: "Broccoli",
    role: "veg",
    kcal: 25,
    protein: 2,
    carbs: 5,
    fat: 0,
    tags: ["vegetarian", "vegan"],
  }),
  item({
    id: "cookie",
    name: "Cookie",
    role: "extra",
    kcal: 200,
    protein: 2,
    carbs: 28,
    fat: 9,
    tags: ["vegetarian"],
    allergens: ["wheat", "milk"],
  }),
  item({ id: "evk-rice", name: "White Rice", hall: "evk", role: "carb" }),
  item({ id: "pancake", name: "Pancake", role: "carb", meals: ["Breakfast"] }),
];
